package com.catalog.demo.controller;

import com.catalog.demo.model.PhoneVO;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@RestController
public class CatalogController {
    @CrossOrigin(origins = "http://localhost:8080")
    @GetMapping(value = "/phones",
            produces = MediaType.APPLICATION_JSON_VALUE)
    public List<PhoneVO> getCatalog(){
        List<PhoneVO> phoneList = new ArrayList<PhoneVO>();

        phoneList.add(new PhoneVO(1,"Xiaomi 12 Pro 5G Negro 256GB","Xiaomi","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","936","zoom-frontal-corporate-xiaomi-12-pro-negro.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(2,"Apple iPhone SE Medianoche 64GB","Apple","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","432","frontal-660-iphone-se-medianoche.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(3,"iPhone 13 mini Verde 128GB","Apple","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","720","frontal-660-iphone-13-mini-verde.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(4,"Samsung Galaxy S22 Negro 128GB","Samsung","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","684","lateral-660-samsung-galaxy-s22-black.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(5,"OPPO Find X5 Lite 5G Negro 256GB","OPPO","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","378","frontal-660-oppo-find-x5-lite-negro-bundle.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(6,"Realme GT2 Negro 128GB","Realme","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","378","frontal-660-realme-gt2-128gb-black.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(7,"HONOR 50 5G Negro 256GB","HONOR","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","350","frontal-660-honor-50-promo-negro.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(8,"Xiaomi Redmi Note 11 Pro 5G Gris 128GB","Xiaomi","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","333","frontal-660-redmi-note-11-pro-5g-gris.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(9,"Apple iPhone 13 Rosa 256GB","Apple","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","918","frontal-660-apple-iphone13-rosa.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(10,"Samsung Galaxy S21 FE 5G Gris 128GB","Samsung","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","594","frontal-660-samsung-galaxy-s21-fe-5g-128gb-grey.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(11,"Xiaomi Mi 11i 5G Negro Cósmico 256GB","Xiaomi","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","432","Frontal660_Mi11i_Negro.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(12,"Apple iPhone 13 Rojo 512GB","Apple","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","1100","frontal-660-apple-iphone13-rojo.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(13,"Nokia G50 5G Azul 64GB","Nokia","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","153","frontal-660-nokia-g50-blue.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(14,"Alcatel 1S Negro 32GB","Alcatel","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","71","Frontal660_Alcatel-1S-2021.png","4.7 inch IPS","A10 Fusion","2"));
        phoneList.add(new PhoneVO(15,"LG G8s ThinQ Negro 128GB","LG","Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","black","477","Frontal660_LGG8_Negro.png","4.7 inch IPS","A10 Fusion","2"));
        return phoneList;

    }
}
